# Generated by Django 3.2 on 2024-11-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thememetadata',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
