# Generated by Django 3.2 on 2024-11-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_userdata'),
        ('portfolio', '0002_alter_thememetadata_date_and_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_json', models.JSONField()),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_portfolio', to='userProfile.jobs')),
            ],
            options={
                'verbose_name_plural': 'final Portfolio',
            },
        ),
    ]
