# Generated by Django 3.2 on 2024-12-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_alter_userdata_job_id'),
        ('portfolio', '0004_alter_portfolio_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='job_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_portfolio', to='userProfile.jobs'),
        ),
    ]
